[build]
  command = "./build.sh"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  GO_VERSION = "1.21"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  directory = "netlify/functions"